server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: greeting-service
          uri: lb://greeting-service
          predicates:
            - Path=/api/v1/greetings/**