server:
  port: 8888


logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG

spring:


  profiles:
    active: jdbc
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: classpath:/config

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:config-server
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true


  h2:
    console:
      enabled: true
